### ISSUE TITLE
add interview questions for react developers

### ISSUE THREAD

**Issue by yanisurbis** [timarney/react-faq#15]
I think it would be great, wouldn't it?

**Comment by yanisurbis** [comment]
https://gist.github.com/gaearon/8fa9fdd2c4197ee0b52894877bf587a4

**Comment by timarney** [comment]
I like the idea.
1. I'm not sure if it's the right fit for this repo - might be just need to give it more thought.
2. Would need to source some questions to get rolling.  Do you have ideas for that?

**Comment by timarney** [comment]
@yanisurbis I found this repo https://github.com/eltonjuan/react-interview-questions/blob/master/ReactInterviewQuestions.md .  If you would like to create a new section called 'Interview Questions' and add a link to that repo link + Dan's link you mentioned that would be great.

**Comment by yanisurbis** [comment]
@timarney Oh, I think that this repo is great. I'm currently rereading the react's docs and think that it would probably be a good idea if we create smth like a _list of questions for every page_ in that docs.
Also probably some _small exercises_ like this one: http://codepen.io/yanisurbis/pen/dpwvxz. And after we can add some _questions that have a vague relation_ to the docs. 

P.S.: Sorry for my English.

**Comment by timarney** [comment]
@yanisurbis I've been rereading the docs as well :) 

I started moving some sections around yesterday to roughly follow the order of the docs so what your saying makes sense as far as questions for each page in the docs.  I like the idea of exercises as well.  

Slight concern with the Readme getting too long ... might need to break things up but, that's for the future.

Please go ahead with what you think makes sense and ping me as needed.

**Comment by timarney** [comment]
@yanisurbis 

Here's a new one for that section (really solid)

https://chandanpandey.com/2016/10/27/the-vital-guide-to-react-js-interviewing/

**Comment by timarney** [comment]
@yanisurbis I went ahead and added the section https://github.com/timarney/react-faq#interview-questions 

Feel free to send a pull request if you have more to add.

Thanks for your contributions.

Closing this for now.
