### ISSUE TITLE
Zero config starter kit

### ISSUE THREAD

**Issue by stereobooster** [timarney/react-faq#21]
Zero config starter kit - this is what FAQ calls "How do I create a new React project?". I believe zero config is the main feature, there are a lot of other template projects from which you can start react app.

I would add one more option: [next.js](https://github.com/zeit/next.js)

**What if I want SASS or LESS or CSSModules with CRA**: [custom-react-scripts](https://github.com/kitze/create-react-app) or eject

**What if I want custom build of bootstrap or foundation with CRA**: [see](https://medium.com/@tacomanator/customizing-create-react-app-aa9ffb88165) or eject

*When ejecting make it in sepparate commit, so you can undo easily 

PS. thanks for FAQ

**Comment by timarney** [comment]
@stereobooster - solid points .

I'm going to rework that section to mention Next.js etc... + https://github.com/mxstbr/react-boilerplate.

I've been waiting for things to settle a bit with CRA  custom-react-scripts  is great and I also have https://github.com/timarney/react-app-rewired (with SASS + CSS Module) examples.

I'll likely have time next week to take care of this.  Thanks for taking the time to give some feedback :)

**Comment by stereobooster** [comment]
PWA for CRA https://github.com/jeffposnick/create-react-pwa

**Comment by timarney** [comment]
Cool I'll check that one out :)
