### ISSUE TITLE
Storybook worth to mention

### ISSUE THREAD

**Issue by stereobooster** [timarney/react-faq#22]
https://voice.kadira.io/react-storybooks-meets-create-react-app-ac8a3f32cc79

**Comment by timarney** [comment]
@stereobooster yes it's definitely worth a mention.  It's a great project. Not sure where to put it i.e. What section / kind of question would you think would be good for that?

**Comment by stereobooster** [comment]
Components -> How to test components?

On the second thought.

How to test components while you developing it?

**Comment by timarney** [comment]
Ya I was thinking something around testing that article says:

>It’s a way to launch a visual development environment for your React component. Using it, you can build a component without running your app.

I'll ping the author and see what he thinks.

**Comment by arunoda** [comment]
@timarney according to these categories, testings seems like a good place.
It's for developing components, but not sure it's suits inside the Components category.

**Comment by timarney** [comment]
@arunoda thanks - I'm thinking I'll start a new Tools Section -

**Link to StoryBook** (A visual way to develop your UI components.  Show them in different states and develop them interactively)

**React Dev Tools**
**Why Did You Update** https://github.com/garbles/why-did-you-update

**Comment by timarney** [comment]
https://github.com/timarney/react-faq#tools

**Comment by arunoda** [comment]
@timarney Superb.
