### ISSUE TITLE
CSS issue in Firefox: <summary> arrow marker hidden due to display: block

### ISSUE THREAD

**Issue by jendowns** [timarney/react-faq#29]
Hey there! 👋

First of all, I love this site. You've put together an awesome resource! 💜

I noticed a little CSS issue: the `<summary>` arrow marker in the `<details>` element at the bottom of your homepage (Beginning with "Additional information to start with...") does not display at all in Firefox (specifically, v 51.01). As a result, in Firefox it looks like the content is a cut-off sentence, rather than a collapsible element with additional hidden info.

The cause of the missing arrow appears to be related to the way Firefox handles `<details>` elements. From the [Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details):

> For cross browser compatible styling hide Firefox's marker by setting `summary { display: block }`

There's a style rule being added (probably as part of a CSS reset?) that sets all `<summary>` elements to `display: block`, which hides the little arrow marker in Firefox. So removing or overriding the display rule for that particular element should fix the issue!

Thanks! Please let me know if you have any questions or concerns.

Best,
Jen

**Comment by timarney** [comment]
Thanks appreciate the kind words.

I'm hoping to find some time next week to fix a few layout issues I'll add that to the list :)

**Comment by timarney** [comment]
Hey @jendowns should be all good on that now.
