### ISSUE TITLE
UX issue in site 

### ISSUE THREAD

**Issue by ajduke** [timarney/react-faq#32]
Upper top level Menu items navigation are not apparent and does not look like primary navigation when i first visited the site.

We can change the color to more darker and closer to each other to make it feel like those are primary navigation

**Comment by timarney** [comment]
Feel free to file a pull request - https://github.com/timarney/react-faq/blob/master/css/menu-desktop.css.

**Comment by ajduke** [comment]
Okay,  here are 2 options I am thinking of 

1- With background black on active 

![image](https://user-images.githubusercontent.com/1594650/27762702-99e46978-5e94-11e7-81cc-ccd23b5ed00c.png)


2 - with border bottom black on active 

![image](https://user-images.githubusercontent.com/1594650/27762711-e0ecc568-5e94-11e7-973f-acb548d19450.png)


What do you think ?

**Comment by timarney** [comment]
Looks good to me.
